apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-deployment
  namespace: default
  annotations:
    # Settings for Prometheus collector
    metric-config.external.prometheus-query.prometheus/prometheus-server: "http://prometheus.monitoring.svc"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 # 50% of 20m
    - type: Pods
      pods:
        metric:
          name: custom_metric
        target:
          type: AverageValue
          averageValue: 20
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
